odom_frame: door4_odom
base_link_frame: door4_link
world_frame: door4_odom

two_d_mode: true

frequency: 50

odom0: /door4/door_velocity_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, true,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_queue_size: 10
