odom_frame: door2_odom
base_link_frame: door2_link
world_frame: door2_odom

two_d_mode: true

frequency: 50

odom0: /door2/door_velocity_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, true,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_queue_size: 10
